[theme]
base = "light"
primaryColor = "#3772FF"
backgroundColor = "#F8F9F8"
secondaryBackgroundColor = "#E6E8E6"
textColor = "#2A2B2A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[browser]
gatherUsageStats = false
